name: assignment-test
on: [push]
jobs:
    full-test:
        container: cuaesd/aesd-autotest:assignment4-buildroot
        runs-on: self-hosted
        timeout-minutes: 120
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - uses: webfactory/ssh-agent@v0.5.3
            with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          - name: Run full test
            with:
                super_secret: ${{ secrets.SECRET_TOKEN }}
            env:
              GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
            run: |
              ./full-test.sh |
              $($SUPER_SECRET)
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
